import { HINDI_ISL_ALIASES } from "@/data/hindi_isl_aliases";
import type { ISLDictionaryEntry } from "@/lib/types";

const DEVANAGARI_RE = /[ऀ-ॿ]/;

/**
 * Tokenise a line into [text, isWord] runs. A "word" is a contiguous run of
 * either Latin alphanumerics (with an internal apostrophe) OR Devanagari
 * characters. A "non-word" is everything else (whitespace, punctuation,
 * em-dashes), preserved verbatim so spacing and punctuation survive the
 * re-emit unchanged. Latin and Devanagari runs are tokenised separately:
 * "खून blood test" produces three word tokens, not one.
 */
export function tokeniseLine(line: string): Array<{ text: string; isWord: boolean }> {
  const out: Array<{ text: string; isWord: boolean }> = [];
  const re = /[A-Za-z0-9]+(?:'[A-Za-z0-9]+)?|[ऀ-ॿ]+/g;
  let last = 0;
  for (const match of line.matchAll(re)) {
    const idx = match.index ?? 0;
    if (idx > last) out.push({ text: line.slice(last, idx), isWord: false });
    out.push({ text: match[0], isWord: true });
    last = idx + match[0].length;
  }
  if (last < line.length) out.push({ text: line.slice(last), isWord: false });
  return out;
}

// Module-level memo — built once per dictionary identity. 10k+ terms × per-line
// regex would be catastrophic; an O(words-in-line) hash lookup is fast.
let cachedIndex: { dict: ISLDictionaryEntry[]; index: Map<string, ISLDictionaryEntry> } | null =
  null;

/**
 * Build a lowercase-keyed lookup map from the ISL dictionary. Memoised on
 * dictionary identity (the dictionary is fetched once per page session and
 * the array reference is stable across renders).
 */
export function getIndex(dictionary: ISLDictionaryEntry[]): Map<string, ISLDictionaryEntry> {
  if (cachedIndex && cachedIndex.dict === dictionary) return cachedIndex.index;
  const index = new Map<string, ISLDictionaryEntry>();
  for (const entry of dictionary) {
    const keys = [entry.term, ...(entry.aliases ?? [])];
    for (const k of keys) {
      const norm = k.toLowerCase().trim();
      if (!norm) continue;
      // First entry wins on collision so the dictionary's natural ordering
      // (alphabetised by sync script) gives stable behaviour.
      if (!index.has(norm)) index.set(norm, entry);
    }
  }
  cachedIndex = { dict: dictionary, index };
  return index;
}

/**
 * Look up a token in the ISL index. For Latin tokens, lowercase the surface
 * form and probe directly. For Devanagari tokens, first translate via the
 * hand-curated Hindi → English alias map, then probe. Keeps the dictionary
 * (auto-generated by sync_isl_dictionary.ts) script-pure while letting Hindi
 * simplifications still chip the same medical / civic vocabulary.
 */
export function resolveEntry(
  surface: string,
  index: Map<string, ISLDictionaryEntry>,
): ISLDictionaryEntry | undefined {
  if (DEVANAGARI_RE.test(surface)) {
    const englishKey = HINDI_ISL_ALIASES[surface];
    if (!englishKey) return undefined;
    return index.get(englishKey);
  }
  return index.get(surface.toLowerCase());
}

/* ───── Critical-span splitter ─────────────────────────────────────────── */
// Matches the verbatim critical-field spans the simplifier inlines in the body.
// Kept private — the regex is an implementation detail; consumers use the
// exported splitOnCriticalSpans function.
const CRITICAL_SPAN_RE = /<span class="critical-field"[\s\S]*?<\/span>/g;

export interface CriticalSegment { kind: "critical"; html: string }
export interface TextSegment { kind: "text"; text: string }
export type Segment = CriticalSegment | TextSegment;

/**
 * Split a section body into alternating text and critical-field-span segments.
 * The sequencer and the renderer both call this first so they walk exactly the
 * same set of plain-text tokens — critical-field HTML is never tokenised.
 */
export function splitOnCriticalSpans(body: string): Segment[] {
  const segments: Segment[] = [];
  let lastIndex = 0;
  for (const match of body.matchAll(CRITICAL_SPAN_RE)) {
    const idx = match.index ?? 0;
    if (idx > lastIndex) segments.push({ kind: "text", text: body.slice(lastIndex, idx) });
    segments.push({ kind: "critical", html: match[0] });
    lastIndex = idx + match[0].length;
  }
  if (lastIndex < body.length) {
    segments.push({ kind: "text", text: body.slice(lastIndex) });
  }
  return segments;
}
