// Hindi-term aliases for the (English-only) ISL dictionary.
//
// The dictionary at data/isl_dictionary.json is regenerated by
// scripts/sync_isl_dictionary.ts from the ISLRTC archive — its terms are
// English, indexed by lowercase. Hindi-script simplified output cannot match
// against that index directly, so this map gives the chip resolver a
// pre-stage: Devanagari token → canonical English key (lowercase) that the
// existing English index will resolve.
//
// Authored by hand for the medical, civic, and legal vocabulary the demo
// documents (discharge summary, court summons, Ayushman rejection, property
// notice) actually contain. Not a complete bilingual lexicon — a hackathon-
// scope curation. Add entries as new demo documents demand them.
//
// Convention:
//   key   — Hindi/Devanagari surface form (lowercase doesn't apply; Devanagari
//           has no case). Use the most common spelling for the concept; add
//           variants by listing the same English key under each variant.
//   value — lowercase English term as it appears (or would appear) in the
//           ISL dictionary `term` field. The chip resolver will look this up
//           in the existing index.

export const HINDI_ISL_ALIASES: Record<string, string> = {
  // ── People & roles ──────────────────────────────────────────────────────
  "डॉक्टर": "doctor",
  "डाॅक्टर": "doctor",
  "चिकित्सक": "doctor",
  "नर्स": "nurse",
  "मरीज़": "patient",
  "मरीज": "patient",
  "रोगी": "patient",
  "वकील": "lawyer",

  // ── Places ──────────────────────────────────────────────────────────────
  "अस्पताल": "hospital",
  "हॉस्पिटल": "hospital",
  "अदालत": "court",
  "कोर्ट": "court",
  "न्यायालय": "court",
  "स्कूल": "school",
  "विद्यालय": "school",
  "कार्यालय": "office",

  // ── Care, treatment, body ───────────────────────────────────────────────
  "दवाई": "medicine",
  "दवा": "medicine",
  "गोली": "tablet",
  "टैबलेट": "tablet",
  "इलाज": "cure heal",
  "सर्जरी": "surgery",
  "ऑपरेशन": "surgery",
  "जांच": "test",
  "जाँच": "test",
  "रिपोर्ट": "report",
  "खून": "blood",
  "रक्त": "blood",
  "दिल": "heart",
  "हृदय": "heart",
  "दर्द": "pain",
  "बुखार": "fever",
  "बीमारी": "disease",
  "रोग": "disease",
  "स्वास्थ्य": "health",
  "तबीयत": "health",
  "टीका": "vaccine",
  "वैक्सीन": "vaccine",
  "खाना": "food",
  "भोजन": "food",
  "पानी": "water",
  "नींद": "sleep",
  "आराम": "rest",

  // ── Time & cadence ──────────────────────────────────────────────────────
  "दिन": "day",
  "महीना": "month",
  "साल": "year",
  "वर्ष": "year",
  "आज": "today",
  "कल": "tomorrow",
  "सुबह": "morning",
  "रात": "night",

  // ── Civic / process vocabulary ──────────────────────────────────────────
  "रुपया": "rupee, money",
  "रुपये": "rupee, money",
  "फॉर्म": "form",
  "आवेदन": "application",
  "नोटिस": "notice notification",
  "तारीख": "date",
  "दिनांक": "date",
  "नाम": "name",
  "पता": "address",
  "फोन": "phone",
  "मोबाइल": "phone",
  "नंबर": "number",
  "पुलिस": "police",
  "सरकार": "government",

  // ── Family & basic identity ─────────────────────────────────────────────
  "माँ": "mother",
  "पिता": "father",
  "बच्चा": "child",
  "परिवार": "family",
};
